### PR TITLE
OfficeOnlineServerDSC: Import DscResource.Common module

### LINKED ISSUE #67: OfficeOnlineServerDSC: Import DscResource.Common module
It would be nice that we can use the DscResource.Common module in this project.

### PR DESCRIPTION
**Pull request by JonasRied**
#### Pull Request (PR) description

Imports DscResource.Common module and replaces Get-LocalizedData from OfficeOnlineServerDsc.Util
#### This Pull Request (PR) fixes the following issues

- Fixes #67

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/68)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/68)* status: all files reviewed, 1 unresolved discussion (waiting on @JonasCassier)

___
*[`src/Modules/OfficeOnlineServerDsc.Util/OfficeOnlineServerDsc.Util.psm1` line 157 at r1](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/68#-Njb0EEuBC8mQKz8sd9g:-Njb0EEuBC8mQKz8sd9h:b712n3x) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/b59653ba16998aea559ce911eef0646ca2e0b33f/src/Modules/OfficeOnlineServerDsc.Util/OfficeOnlineServerDsc.Util.psm1#L157)):*
> ```PowerShell
>         localized data for this helper module (see directly after this function).
> #>
> # function Get-LocalizedData
> ```

We can remove this function now, the changes looks okay.

**Comment by johlju** [comment]
Awesome work getting sending in this change! Thank you!

**Review by JonasRied — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/68)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[`src/Modules/OfficeOnlineServerDsc.Util/OfficeOnlineServerDsc.Util.psm1` line 157 at r1](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/68#-Njb0EEuBC8mQKz8sd9g:-NjbA91N51ONG4LZUKoq:b-896fix) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/b59653ba16998aea559ce911eef0646ca2e0b33f/src/Modules/OfficeOnlineServerDsc.Util/OfficeOnlineServerDsc.Util.psm1#L157)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We can remove this function now, the changes looks okay.
</blockquote></details>

Done.

**Comment by JonasRied** [comment]
> Awesome work getting sending in this change! Thank you!

I'm just starting to participate in the DSC community. It was/is a great learning experience for me. Thank you, too.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/68#-:-NjcJB_yAJCIQtY7El_A:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JonasCassier)

**Comment by johlju** [comment]
Thank you for contributing again, this is merged so we can start using commands from the common module now. 🙂

**Pull request merged**
