### PR TITLE
OfficeOnlineServerHost: New resource proposal

### LINKED ISSUE #62: OfficeOnlineServerHost: New resource proposal
### Description
The resource should be used to manage the OfficeWebAppsHosts. 
https://learn.microsoft.com/en-us/powershell/module/officewebapps/new-officewebappshost?view=officewebapps-ps
### Proposed properties
[Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"),ValueMap{"Yes"},Values{"Yes"}] String IsSingleInstance;
[Write, Description("Ensure Present or Absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
[Write, Description("Host domains to which Office Online Server allows file operations requests")] String AllowList[];

### PR DESCRIPTION
**Pull request by JonasRied**
#### Pull Request (PR) description

OfficeOnlineServerHost: New resource proposal

#### This Pull Request (PR) fixes the following issues

- Fixes #62 
#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/63)

### CODE REVIEW

**Comment by johlju** [comment]
I think this resource would be better if it instead of AllowList had the parameters `Domains`, `DomainsToInclude` and `DomainsToExclude`.  Using the parameter `Domains` would override (remove) any already configured domains, passing an empty array would remove any configured domains (if. that is a possible scenario). The parameter `DomainsToExclude` would remove any domain that is present, and leave the rest. The parameter `DomainsToInclude` would add any domain that is not present, and leave the rest. 

I think parameter `Ensure` should not be used in this resource as `Ensure` normally is used when ensuring _one_ object can only be present or absent, for example one host domain, one user account, etc. It would also be strange if there is another property is added to the resource, what property would you then want to ensure is present or absent. 🙂

**Comment by JonasRied** [comment]
I have adapted the resource according to your suggestions. 
Can you please take another look? I still need to change the unit tests.

**Review by johlju — COMMENTED** [review]
I see duplicate files. It seems you have copied the resource folder into the resource folder (duplicate folder names here): src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1

I will review as soon as I have time.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/63#-:-NiVJm9eCnMsyveeZSKG:b-qi0k6h)* status: 0 of 12 files reviewed, all discussions resolved

**Comment by JonasRied** [comment]
Thx. I have removed the duplicate folder.

**Comment by johlju** [comment]
@JonasCassier I merged a PR updating all the pipeline files, so if your rebase the pipeline in this PR should run correctly.

**Comment by JonasRied** [comment]
@johlju I don't have much experience with "git rebase" yet. But it seems to have worked. In any case, the pipeline has now run successfully :) .

**Comment by johlju** [comment]
> @johlju I don't have much experience with "git rebase" yet. But it seems to have worked. In any case, the pipeline has now run successfully :) .

Looks good! Now days you can configure git to do rebase on `git pull` so it is auto magic :) Either case, `git pull` works too 🙂  But if you are interested, this is the way I do it (kind of like having the control of doing it myself 😃): https://dsccommunity.org/guidelines/contributing/#resolve-merge-conflicts

**Comment by johlju** [comment]
I will review as soon as I have time. Might take a few days.

**Comment by johlju** [comment]
@JonasCassier actually looking at it now, a rebase is needed. The diff have all the files that were changed and merged in a previous PR. Can you try to rebase according to this link? https://dsccommunity.org/guidelines/contributing/#resolve-merge-conflicts
You can "backup" your current local branch by running `git branch my-backup-branch-name`. Let me know if you need any help.

**Comment by JonasRied** [comment]
@johlju i tried according to the link but i get some errors.

1. Rebase the local branch master

PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git branch Feature/BackupOfOfficeWebAppsHost
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git fetch origin/master
fatal: 'origin/master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git fetch origin master 
From https://github.com/JonasCassier/OfficeOnlineServerDsc
branch            master     -> FETCH_HEAD
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git rebase origin/master
Current branch master is up to date.
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git push master --force
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.      

Please make sure you have the correct access rights
and the repository exists.
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git push origin/master --force
fatal: 'origin/master' does not appear to be a git repository
fatal: Could not read from remote repository.      

Please make sure you have the correct access rights
and the repository exists.

2. Rebase your working branch

PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git checkout Feature/OfficeWebAppsHost
Switched to branch 'Feature/OfficeWebAppsHost'
Your branch is up to date with 'origin/Feature/OfficeWebAppsHost'.
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git rebase main
fatal: invalid upstream 'main'
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git rebase origin/main
fatal: invalid upstream 'origin/main'
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git pull --all
Already up to date.
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git rebase main       
fatal: invalid upstream 'main'
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git rebase origin/main
fatal: invalid upstream 'origin/main'
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc>

**Comment by JonasRied** [comment]
@johlju i tried according to the link but i get some errors.

Rebase the local branch master
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git branch Feature/BackupOfOfficeWebAppsHost
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git fetch origin/master
fatal: 'origin/master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git fetch origin master
From https://github.com/JonasCassier/OfficeOnlineServerDsc
branch master -> FETCH_HEAD
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git rebase origin/master
Current branch master is up to date.
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git push master --force
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git push origin/master --force
fatal: 'origin/master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Rebase your working branch
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git checkout Feature/OfficeWebAppsHost
Switched to branch 'Feature/OfficeWebAppsHost'
Your branch is up to date with 'origin/Feature/OfficeWebAppsHost'.
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git rebase main
fatal: invalid upstream 'main'
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git rebase origin/main
fatal: invalid upstream 'origin/main'
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git pull --all
Already up to date.
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git rebase main
fatal: invalid upstream 'main'
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc> git rebase origin/main
fatal: invalid upstream 'origin/main'
PS C:\Users\Jonas Cassier\Documents\Code\OfficeOnlineServerDsc>

According to GitHub, my fork is also up to date with dsccommunity/OfficeOnlineServerDsc:master.

Any ideas ?

**Comment by johlju** [comment]
Can you give me the output of `git remote -v` when you stand it the local repository folder. We must set up the remotes correct first.

**Comment by JonasRied** [comment]
@johlju 
git remote -v
origin  https://github.com/JonasCassier/OfficeOnlineServerDsc.git (fetch)
origin  https://github.com/JonasCassier/OfficeOnlineServerDsc.git (push)

**Comment by JonasRied** [comment]
Today git behaves different. I get some output about the merge conflicts:

git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.

git push master --force
fatal: 'master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

git checkout Feature/officeWebAppsHost
Switched to branch 'Feature/officeWebAppsHost'

git rebase master   
Auto-merging src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1
CONFLICT (add/add): Merge conflict in src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1
Auto-merging src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.schema.mof
CONFLICT (add/add): Merge conflict in src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.schema.mof        
Auto-merging src/DSCResources/MSFT_OfficeOnlineServerHost/en-US/MSFT_OfficeOnlineServerHost.strings.psd1
CONFLICT (add/add): Merge conflict in src/DSCResources/MSFT_OfficeOnlineServerHost/en-US/MSFT_OfficeOnlineServerHost.strings.psd1
error: could not apply 603847c... Create new resource MSFT_OfficeOnlineServerHost
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 603847c... Create new resource MSFT_OfficeOnlineServerHost

i try to resolve them

**Comment by johlju** [comment]
Still to many files because you have no remote to the upstream repo that have the new changes, So in your case you need another remote for the upstream to be able to get them down to you local repository. 

I think this should work for you, let me know if anything fails:

```bash
# add remote to upstream
git remote add upstream https://github.com/dsccommunity/OfficeOnlineServerDsc.git

# fetch changes from upstream branch master
git fetch upstream master

# rebase the local repository branch master
git checkout master
git rebase upstream/master

# push the updated branch master to your forked GitHub repository
git push origin --force

# Rebase the working (PR) branch using the updated local branch master
git checkout Feature/OfficeWebAppsHost
git rebase upstream/master

# Fix any conflicts as you did before

# When there are no more conflicts, run the following to update the working branch in your forked GitHub repository (which will update the PR)
git push origin --force
```

**Comment by JonasRied** [comment]
@johlju I got into a mess of merge conflicts, so I created a new Branch:

git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.

git fetch upstream master
From https://github.com/dsccommunity/OfficeOnlineServerDsc
 * branch            master     -> FETCH_HEAD

git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.

git rebase upstream/master
Current branch master is up to date.

git push origin --force
Everything up-to-date
git branch Feature/OfficeOnlineServerHost
git checkout Feature/OfficeOnlineServerHost

Here is the new PR https://github.com/dsccommunity/OfficeOnlineServerDsc/pull/66

**Comment by JonasRied** [comment]
duplicates https://github.com/dsccommunity/OfficeOnlineServerDsc/pull/66

**Pull request closed without merging**
