### PR TITLE
Prep for 1.2.0.0 release

### PR DESCRIPTION
**Pull request by NikCharlebois**
@kwirkykat All set for DSC Kit release

1.2.0.0

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/officeonlineserverdsc/19)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@NikCharlebois Looks like tests are failing, but I will release this as soon as they are fixed. Just let me know

**Comment by NikCharlebois** [comment]
@kwirkykat all tests are now passing. please publish when you have a chance. Thanks

**Comment by kwirkykat** [comment]
@NikCharlebois Please add release notes to the Changelog file and the module manifest

**Comment by NikCharlebois** [comment]
@kwirkykat  Done. Thanks

**Pull request merged**
