### PR TITLE
OfficeOnlineServerHost: New resource proposal

### LINKED ISSUE #62: OfficeOnlineServerHost: New resource proposal
### Description
The resource should be used to manage the OfficeWebAppsHosts. 
https://learn.microsoft.com/en-us/powershell/module/officewebapps/new-officewebappshost?view=officewebapps-ps
### Proposed properties
[Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"),ValueMap{"Yes"},Values{"Yes"}] String IsSingleInstance;
[Write, Description("Ensure Present or Absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
[Write, Description("Host domains to which Office Online Server allows file operations requests")] String AllowList[];

### PR DESCRIPTION
**Pull request by JonasRied**
#### Pull Request (PR) description

Adds new resource OfficeOnlineServerHost
Replacement of https://github.com/dsccommunity/OfficeOnlineServerDsc/pull/63

#### This Pull Request (PR) fixes the following issues

- Fixes #62
- Closes #63 
#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
This is what I had time for today. Barely started with the review, but now there are a few things for you to look over. :slightly_smiling_face: 

> Reviewed 1 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-:-NizPVuC1yNbbs73botf:bwgxpr6)* status: 1 of 10 files reviewed, 8 unresolved discussions (waiting on @JonasCassier)

___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 42 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizIdM18P7GFsk5AMV_:-NizIdM18P7GFsk5AMVa:b-rzs4rl) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L42)):*
> ```PowerShell
>     Test-OfficeOnlineServerHostPSBoundParameters @PSBoundParameters
> 
>     $nullReturn = $PSBoundParameters
> ```

SUggest using `@{} + $PSBoundParameters` so when get a new hashtable, otherwise we just get the ref of a type `System.Management.Automation.PSBoundParametersDictionary` (which is not a hashtable which we should return) and also, any changes made to the variable (in a future PR) will also change the values of `PSBoundParameters` since we get a ref to the type `PSBoundParametersDictionary`.
___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 43 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizLS1cAJ0p7UmeyIAv:-NizLS1cAJ0p7UmeyIAw:b-57ggew) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L43)):*
> ```PowerShell
> 
>     $nullReturn = $PSBoundParameters
>     $nullReturn.Domains = @()
> ```

Should this also be set to the type `[System.Array]` so we consequent (it is set to the type below in another code path).
___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 45 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizLldFEu55vfDzPx7a:-NizLldFEu55vfDzPx7b:b-luf353) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L45)):*
> ```PowerShell
>     $nullReturn.Domains = @()
> 
>     try
> ```

The `try-catch` should only be around the command that we catch, so that we can catch errors and throw for things that should be terminating errors (those can be set in a future PR. But here I would rather not see we use `try-catch` to switch code path. I rather see that the catch-statement sets a boolean value that we evaluate to determine if we could access the needed property, then return a hashtable accordingly.  
___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 47 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizKzNr-6DO9ItOfkM5:-NizKzNs9yYrijJxJNmR:b-2zietr) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L47)):*
> ```PowerShell
>     try
>     {
>         return @{
> ```

We should always return all properties in the hashtable (as `null` or the value passed if they cannot be set to a current configured value).
___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 49 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizLLBa1b8mTsvSskaL:-NizLLBa1b8mTsvSskaM:b-5gi7oz) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L49)):*
> ```PowerShell
>         return @{
>             IsSingleInstance = 'Yes'
>             Domains          = [Array](Get-OfficeWebAppsHost -ErrorAction 'Stop').AllowList
> ```

We shuould use the full type name `[System.Array]`.
___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 70 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizOFtGCWyGO2z4Skmg:-NizOFtGCWyGO2z4Skmh:b-inggpt) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L70)):*
> ```PowerShell
>         [Parameter()]
>         [System.String[]]
>         $Domains,
> ```

Thw parameter `Domains` should be mutually exclusive to `DomainsToInclude` and `DomainsToExclude`. All three should not be allowed to be used at once., Only `DomainsToInclude` and `DomainsToExclude` should be bale to be used at the same time.

There is a command [`Assert-BoundParameter`](https://github.com/dsccommunity/DscResource.Common#assert-boundparameter) in the module DscResource.Common that can help with this. Though I see this module does not use the helper module (yet). There is a [blog post](https://dsccommunity.org/blog/use-dscresource-common-functions-in-module/) on how to add the helper module to a DSC module, though this might break other modules that need to be fixed, so I think that should be done in a separate PR. So another option is to copy the code from DscResource.Common and put it in # OfficeOnlineServerDsc.Util. :thinking: You decide :smiley: 
___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 81 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizMeJP8Lxw3sV2nezp:-NizMeJQA_FDT3m7j689:b672ra4) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L81)):*
> ```PowerShell
>     )
> 
>     Write-Verbose -Message "Updating Office Online Server Farm host allow list"
> ```

Can we move the strings to the localization files? Throughout the code. Then use them similar to here: https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/7358992166a7f977dbce96ce53773f34fbaede76/src/DSCResources/MSFT_OfficeOnlineServerFarm/MSFT_OfficeOnlineServerFarm.psm1#L522
___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 96 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizN4eCA44I3--cPfVZ:-NizN4eCA44I3--cPfV_:b-ct5a3z) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L96)):*
> ```PowerShell
>         if ($null -eq $Domains)
>         {
>             $PSBoundParameters.Add('DomainsToExclude', $CurrentValues.Domains) | Out-Null
> ```

See previous comment about `$PSBoundParameters`. We should not add properties to the `$PSBoundParameters` because then we cannot determine if they were actually passed by the user/configuration. Suggest using a new hashtable here to control the flow.

**Review by JonasRied — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66)* status: 1 of 10 files reviewed, 8 unresolved discussions (waiting on @johlju)

___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 43 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizLS1cAJ0p7UmeyIAv:-Nj8oDX1Cj4sDGglurOF:b5z86al) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L43)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should this also be set to the type `[System.Array]` so we consequent (it is set to the type below in another code path).
</blockquote></details>

I don't quite understand what you mean by that. @() is of type [System.Array]. Or do you mean something like [System.Array]@()?
___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 49 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizLLBa1b8mTsvSskaL:-Nj8twCT7x5umfCGnO98:b-896fix) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L49)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We shuould use the full type name `[System.Array]`.
</blockquote></details>

Done.
___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 81 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizMeJP8Lxw3sV2nezp:-Nj8zeJD7vru3vJh-z4s:b-896fix) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L81)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we move the strings to the localization files? Throughout the code. Then use them similar to here: https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/7358992166a7f977dbce96ce53773f34fbaede76/src/DSCResources/MSFT_OfficeOnlineServerFarm/MSFT_OfficeOnlineServerFarm.psm1#L522
</blockquote></details>

Done.
___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 96 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizN4eCA44I3--cPfVZ:-Nj90jbdDcclWInD4fDA:b-896fix) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L96)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

See previous comment about `$PSBoundParameters`. We should not add properties to the `$PSBoundParameters` because then we cannot determine if they were actually passed by the user/configuration. Suggest using a new hashtable here to control the flow.
</blockquote></details>

Done.

**Review by JonasRied — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66)* status: 1 of 10 files reviewed, 8 unresolved discussions (waiting on @johlju)

___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 70 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizOFtGCWyGO2z4Skmg:-NjYWs8X4C2LDVeD_JsT:b-e2nek3) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L70)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Thw parameter `Domains` should be mutually exclusive to `DomainsToInclude` and `DomainsToExclude`. All three should not be allowed to be used at once., Only `DomainsToInclude` and `DomainsToExclude` should be bale to be used at the same time.

There is a command [`Assert-BoundParameter`](https://github.com/dsccommunity/DscResource.Common#assert-boundparameter) in the module DscResource.Common that can help with this. Though I see this module does not use the helper module (yet). There is a [blog post](https://dsccommunity.org/blog/use-dscresource-common-functions-in-module/) on how to add the helper module to a DSC module, though this might break other modules that need to be fixed, so I think that should be done in a separate PR. So another option is to copy the code from DscResource.Common and put it in # OfficeOnlineServerDsc.Util. :thinking: You decide :smiley:
</blockquote></details>

I use Test-OfficeOnlineServerHostPSBoundParameters for this. I suggest to proceed with this function first and in a second PR I try to import 'DSCResource.Common'.  Okay?

**Review by JonasRied — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66)* status: 1 of 10 files reviewed, 8 unresolved discussions (waiting on @johlju)

___
*[`src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1` line 70 at r2](https://reviewable.io/reviews/dsccommunity/OfficeOnlineServerDsc/66#-NizOFtGCWyGO2z4Skmg:-NjZZYCR1BDd0pgyzqFi:b8ncf82) ([raw file](https://github.com/dsccommunity/OfficeOnlineServerDsc/blob/9a1849f472523be3dd3ecfcc35c8fbedb47be267/src/DSCResources/MSFT_OfficeOnlineServerHost/MSFT_OfficeOnlineServerHost.psm1#L70)):*
<details><summary><i>Previously, JonasCassier (Jonas Cassier) wrote…</i></summary><blockquote>

I use Test-OfficeOnlineServerHostPSBoundParameters for this. I suggest to proceed with this function first and in a second PR I try to import 'DSCResource.Common'.  Okay?
</blockquote></details>

I have created another PR https://github.com/dsccommunity/OfficeOnlineServerDsc/pull/68 to import DscResource.Common into this project. Maybe we can merge that PR first?

**Comment by johlju** [comment]
The other PR is merged so we can rebase this and use the commands from the common module! 🙂

**Comment by JonasRied** [comment]
@johlju I have included the functions from DSCResource.Common in this resource. But I have no idea what I am doing wrong with git rebase. I have synchronized my fork JonasCassier/OfficeOnlineServerDsc:master with dsccommunity/OfficeOnlineServerDsc:master. Then I rebased Feature/OfficeOnlineServerHost with my master. And now we have the same mess as last time :(.

**Pull request closed without merging**
